# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1842, 971)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OpenImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenImageButton.setGeometry(QtCore.QRect(250, 30, 171, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OpenImageButton.setFont(font)
        self.OpenImageButton.setObjectName("OpenImageButton")
        self.loadedImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.loadedImageLabel.setGeometry(QtCore.QRect(250, 190, 520, 640))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loadedImageLabel.setFont(font)
        self.loadedImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.loadedImageLabel.setScaledContents(False)
        self.loadedImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loadedImageLabel.setWordWrap(False)
        self.loadedImageLabel.setIndent(2)
        self.loadedImageLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.loadedImageLabel.setObjectName("loadedImageLabel")
        self.detectPoresButton = QtWidgets.QPushButton(self.centralwidget)
        self.detectPoresButton.setGeometry(QtCore.QRect(830, 860, 171, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.detectPoresButton.setFont(font)
        self.detectPoresButton.setObjectName("detectPoresButton")
        self.OutputImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.OutputImageLabel.setGeometry(QtCore.QRect(1070, 150, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.OutputImageLabel.setFont(font)
        self.OutputImageLabel.setObjectName("OutputImageLabel")
        self.InputImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.InputImageLabel.setGeometry(QtCore.QRect(250, 150, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.InputImageLabel.setFont(font)
        self.InputImageLabel.setObjectName("InputImageLabel")
        self.predictedImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.predictedImageLabel.setGeometry(QtCore.QRect(1070, 190, 520, 641))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.predictedImageLabel.setFont(font)
        self.predictedImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.predictedImageLabel.setScaledContents(False)
        self.predictedImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.predictedImageLabel.setWordWrap(False)
        self.predictedImageLabel.setIndent(2)
        self.predictedImageLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.predictedImageLabel.setObjectName("predictedImageLabel")
        self.configurationGroupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.configurationGroupbox.setGeometry(QtCore.QRect(780, 490, 281, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.configurationGroupbox.setFont(font)
        self.configurationGroupbox.setFlat(False)
        self.configurationGroupbox.setCheckable(False)
        self.configurationGroupbox.setObjectName("configurationGroupbox")
        self.line = QtWidgets.QFrame(self.configurationGroupbox)
        self.line.setGeometry(QtCore.QRect(0, 30, 281, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.configurationGroupbox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 243, 106))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.confidenceLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.confidenceLabel.setFont(font)
        self.confidenceLabel.setObjectName("confidenceLabel")
        self.verticalLayout.addWidget(self.confidenceLabel)
        self.confidenceSlider = QtWidgets.QSlider(self.layoutWidget)
        self.confidenceSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.confidenceSlider.setAutoFillBackground(False)
        self.confidenceSlider.setMaximum(99)
        self.confidenceSlider.setSingleStep(1)
        self.confidenceSlider.setProperty("value", 75)
        self.confidenceSlider.setSliderPosition(75)
        self.confidenceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.confidenceSlider.setInvertedAppearance(False)
        self.confidenceSlider.setInvertedControls(False)
        self.confidenceSlider.setObjectName("confidenceSlider")
        self.verticalLayout.addWidget(self.confidenceSlider)
        self.maxDetectionsLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.maxDetectionsLabel.setFont(font)
        self.maxDetectionsLabel.setObjectName("maxDetectionsLabel")
        self.verticalLayout.addWidget(self.maxDetectionsLabel)
        self.maxDetectionsSlider_2 = QtWidgets.QSlider(self.layoutWidget)
        self.maxDetectionsSlider_2.setMaximum(1000)
        self.maxDetectionsSlider_2.setProperty("value", 100)
        self.maxDetectionsSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.maxDetectionsSlider_2.setObjectName("maxDetectionsSlider_2")
        self.verticalLayout.addWidget(self.maxDetectionsSlider_2)
        self.detectorsTypesGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.detectorsTypesGroupBox.setGeometry(QtCore.QRect(780, 190, 281, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.detectorsTypesGroupBox.setFont(font)
        self.detectorsTypesGroupBox.setObjectName("detectorsTypesGroupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.detectorsTypesGroupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 241, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Yolov5DetectorCheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Yolov5DetectorCheckBox.setFont(font)
        self.Yolov5DetectorCheckBox.setObjectName("Yolov5DetectorCheckBox")
        self.verticalLayout_2.addWidget(self.Yolov5DetectorCheckBox)
        self.MaskRcnnCheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.MaskRcnnCheckBox.setFont(font)
        self.MaskRcnnCheckBox.setObjectName("MaskRcnnCheckBox")
        self.verticalLayout_2.addWidget(self.MaskRcnnCheckBox)
        self.line_2 = QtWidgets.QFrame(self.detectorsTypesGroupBox)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 281, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.spinnerLabel = QtWidgets.QLabel(self.centralwidget)
        self.spinnerLabel.setGeometry(QtCore.QRect(890, 500, 64, 64))
        self.spinnerLabel.setText("")
        self.spinnerLabel.setObjectName("spinnerLabel")
        self.LoadBlockOfImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadBlockOfImageButton.setGeometry(QtCore.QRect(250, 70, 171, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LoadBlockOfImageButton.setFont(font)
        self.LoadBlockOfImageButton.setObjectName("LoadBlockOfImageButton")
        self.LoadAnnotationsJsonButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadAnnotationsJsonButton.setGeometry(QtCore.QRect(250, 110, 171, 34))
        self.LoadAnnotationsJsonButton.setObjectName("LoadAnnotationsJsonButton")
        self.YoloModelsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.YoloModelsComboBox.setGeometry(QtCore.QRect(780, 380, 281, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.YoloModelsComboBox.setFont(font)
        self.YoloModelsComboBox.setObjectName("YoloModelsComboBox")
        self.MaskRcnnBackboneComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.MaskRcnnBackboneComboBox.setGeometry(QtCore.QRect(780, 440, 281, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.MaskRcnnBackboneComboBox.setFont(font)
        self.MaskRcnnBackboneComboBox.setObjectName("MaskRcnnBackboneComboBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 360, 161, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(780, 420, 231, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1300, 840, 301, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.number_of_pores_detected_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.number_of_pores_detected_label.setFont(font)
        self.number_of_pores_detected_label.setText("")
        self.number_of_pores_detected_label.setAlignment(QtCore.Qt.AlignCenter)
        self.number_of_pores_detected_label.setObjectName("number_of_pores_detected_label")
        self.verticalLayout_3.addWidget(self.number_of_pores_detected_label)
        self.RealPoresLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RealPoresLabel.setFont(font)
        self.RealPoresLabel.setText("")
        self.RealPoresLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RealPoresLabel.setObjectName("RealPoresLabel")
        self.verticalLayout_3.addWidget(self.RealPoresLabel)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1070, 840, 225, 72))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.openDetectedImageButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.openDetectedImageButton.setFont(font)
        self.openDetectedImageButton.setObjectName("openDetectedImageButton")
        self.verticalLayout_4.addWidget(self.openDetectedImageButton)
        self.showRealMaskCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.showRealMaskCheckBox.setFont(font)
        self.showRealMaskCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.showRealMaskCheckBox.setObjectName("showRealMaskCheckBox")
        self.verticalLayout_4.addWidget(self.showRealMaskCheckBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1842, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fingeprint sweat pores detector"))
        self.OpenImageButton.setText(_translate("MainWindow", "Load full image"))
        self.loadedImageLabel.setText(_translate("MainWindow", "No image to display"))
        self.detectPoresButton.setText(_translate("MainWindow", "Detect Pores"))
        self.OutputImageLabel.setText(_translate("MainWindow", "Output image:"))
        self.InputImageLabel.setText(_translate("MainWindow", "Input image:"))
        self.predictedImageLabel.setText(_translate("MainWindow", "No image to display"))
        self.configurationGroupbox.setTitle(_translate("MainWindow", "Attributes settings:"))
        self.confidenceLabel.setText(_translate("MainWindow", "Confidence: 0,75"))
        self.maxDetectionsLabel.setText(_translate("MainWindow", "Max detections: 100"))
        self.detectorsTypesGroupBox.setTitle(_translate("MainWindow", "Detector type:"))
        self.Yolov5DetectorCheckBox.setText(_translate("MainWindow", "YOLOv5 (One-stage)"))
        self.MaskRcnnCheckBox.setText(_translate("MainWindow", "Mask R-CNN (Two-stage)"))
        self.LoadBlockOfImageButton.setText(_translate("MainWindow", "Load image part"))
        self.LoadAnnotationsJsonButton.setText(_translate("MainWindow", "Load JSON annotations"))
        self.label_3.setText(_translate("MainWindow", "YOLOv5 model type:"))
        self.label_4.setText(_translate("MainWindow", "Mask R-CNN Backbone type:"))
        self.openDetectedImageButton.setText(_translate("MainWindow", "Open image in new window"))
        self.showRealMaskCheckBox.setText(_translate("MainWindow", "Show real masks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
